updated spec

diff --git a/rootfs/spec b/rootfs/spec
--- a/rootfs/spec
+++ b/rootfs/spec
@@ -3,6 +3,11 @@ echo "Running application quality approvement..."
 
 set -e
 
+if [ -z $RAILS_ENV ]; then
+  echo "Environment error... RAILS_ENV should be test, currently is empty!"
+  exit 1
+fi
+
 if [ ! "$RAILS_ENV" = "test" ]; then
   echo "Environment error... RAILS_ENV should be test, currently is $RAILS_ENV"
   exit 1
